### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by leonardopardo**
neo4j service and GUI

### CODE REVIEW

**Comment by leonardopardo** [comment]
Load Neo4J service and GUI imagen, it have a generic authentication and volume filesystem settings.

**Review by ralcorta — CHANGES_REQUESTED** [review]
Excellent, you just need to change where the volumes are saved. Put neo4j before each folder like:
 - ./neo4j/data:/data
That is to have a cleaner folder structure.

After that add that path to the .gitignore file and just need to add this featrue to the Readme.md.

**Review by ralcorta — CHANGES_REQUESTED** [review]
Remember, update the README.md file to have up-to-date documentation.

**Review by ralcorta — APPROVED** [review]
Perfect!

**Pull request merged**
